export const GET_QUESTIONS_DATA_SUCCESS = "GET_QUESTIONS_DATA_SUCCESS";
export const GET_QUESTIONS_DATA_LOADING = "GET_QUESTIONS_DATA_LOADING";
export const GET_QUESTIONS_DATA_ERROR = "GET_QUESTIONS_DATA_ERROR";
